import csv

# we need to install faker by running the following command in the terminal (pip/pipenv install faker)
from faker import Faker

fake = Faker()

with open('users.csv', mode='w') as file:
    # csv.writer expects a list of values
    # RU: csv.writer ожидает список значений
    file_writer = csv.writer(
        file, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)

    # file      =>  file object to write to (created with open())
                # RU: объект файла для записи (созданный с помощью open())
    # delimiter => character used to separate fields
                # RU: символ, используемый для разделения полей
    # quotechar => character used to quote fields containing special characters
                # RU: символ, используемый для заключения полей, содержащих специальные символы
    # quoting   => controls when quotes should be generated by the writer
                # RU: управляет тем, когда кавычки должны быть сгенерированы писателем

    file_writer.writerow(['first_name', 'last_name', 'email', 'bio'])

    for _ in range(100):
        file_writer.writerow(
            [fake.first_name(), fake.last_name(), fake.email(), fake.text()])
    file.close()


with open('users.csv') as f:
    for l in f.readlines():
        el = l.split(",")
        if not el[0].isspace() and not el == "\n":
            print("Full name is: ", el[0],  el[1])
    f.close()
